#!/usr/bin/env python3
"""Generate a Flyway migration that loads data/wi_hospitals_cms.json into the hospitals table (see V10).

Usage (from the repo root):
    python3 scripts/cms_hospitals_to_sql.py data/wi_hospitals_cms.json \
        backend/src/main/resources/db/migration/V11__load_cms_wi_hospitals.sql

To refresh the snapshot, re-download from the CMS API (state = WI), e.g.
    https://data.cms.gov/provider-data/api/1/datastore/query/xubh-q36u/0?conditions[0][property]=state&conditions[0][value]=WI&limit=500
then write the output to a NEW migration version (Flyway never re-runs an applied one), upserting by
cms_facility_id so existing hospital ids, and the forum comments attached to them, are kept.
"""

import json
import re
import sys
import uuid

# Stable ids: the same CMS facility always gets the same UUID.
HOSPITAL_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, "https://vigilant-health-compass/hospitals")

KEEP_UPPER = {"UW", "SSM", "HSHS", "VA", "NE", "NW", "SE", "SW", "LLC", "US", "MCW", "II", "III", "WI", "SBH"}
SMALL = {"OF", "AND", "THE", "AT", "IN", "FOR", "ON", "DU", "D/B/A"}
EXPAND = {"CTR": "Center", "HOSP": "Hospital", "MED": "Medical", "MEM": "Memorial", "CO": "County", "HLTH": "Health",
          "SYSTM": "System", "HLTHCARE": "Healthcare"}
SPECIAL = {"THEDACARE": "ThedaCare", "PROHEALTH": "ProHealth", "UNITYPOINT": "UnityPoint", "BAYCARE": "BayCare"}
ORDINAL = re.compile(r"(\d+)(ST|ND|RD|TH)", re.IGNORECASE)


def title(text):
    """'AURORA MEDICAL CTR MANITOWOC COUNTY' -> 'Aurora Medical Center Manitowoc County'."""
    words = []
    for i, word in enumerate(text.split()):
        if word.startswith("(") and word.endswith(")"):
            words.append(word.upper())  # parenthesized abbreviations, e.g. "(MMC-BD)"
            continue
        words.append("-".join(title_word(part, first=(i == 0 and j == 0)) for j, part in enumerate(word.split("-"))))
    return " ".join(words)


def title_word(word, first):
    core = word.strip(",.()&")
    if not core:
        return word
    upper = core.upper()
    if upper in SPECIAL:
        replacement = SPECIAL[upper]
    elif ORDINAL.fullmatch(core):
        replacement = ORDINAL.sub(lambda m: m.group(1) + m.group(2).lower(), core)  # "22ND" -> "22nd"
    elif upper.startswith("MC") and len(core) > 3 and core.isalpha():
        replacement = "Mc" + core[2].upper() + core[3:].lower()  # "MCHENRY" -> "McHenry"
    elif upper in EXPAND:
        replacement = EXPAND[upper]
    elif upper in KEEP_UPPER or any(ch.isdigit() for ch in core) or (len(core) == 1 and core.isalpha()):
        replacement = upper  # acronyms, "N115", direction letters like "S"
    elif upper in SMALL and not first:
        replacement = core.lower()
    else:
        replacement = core[:1].upper() + core[1:].lower()
    return word.replace(core, replacement, 1)


def sql(value):
    if value is None or value == "":
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def main(src, dest):
    with open(src) as f:
        data = json.load(f)

    rows = []
    for h in data["hospitals"]:
        rating = h["hospital_overall_rating"]
        rows.append("(" + ", ".join([
            sql(str(uuid.uuid5(HOSPITAL_NAMESPACE, h["facility_id"]))),
            sql(h["facility_id"]),
            sql(title(h["facility_name"])),
            sql(title(h["address"])),
            sql(title(h["citytown"])),
            sql(h["state"]),
            sql(h["zip_code"]),
            sql(title(h["countyparish"])),
            sql(h["telephone_number"]),
            sql(h["hospital_type"]),
            sql(h["hospital_ownership"]),
            sql(h["emergency_services"] == "Yes"),
            sql(int(rating) if re.fullmatch(r"[1-5]", rating) else None),
        ]) + ")")

    values = ",\n".join(rows)
    out = f"""-- GENERATED by scripts/cms_hospitals_to_sql.py from data/wi_hospitals_cms.json -- do not edit by hand.
-- Source: {data["source"]} ({data["url"]}), {data["query"]}, retrieved {data["retrieved"]}.
-- {len(rows)} hospitals.

insert into hospitals (id, cms_facility_id, name, address, city, state, postal_code, county, phone, hospital_type, ownership, emergency_services, star_rating) values
{values};
"""
    with open(dest, "w") as f:
        f.write(out)
    print(f"Wrote {dest}: {len(rows)} hospitals")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
