#!/usr/bin/env python3
"""Generate the Flyway migration that loads Healthcare Near Me data (see V13):

  data/wi_zip_centers_census.json            -> zip_centers
  data/wi_place_centers_census.json          -> place_centers
  data/wi_community_health_centers_hrsa.json -> community_health_centers
  + hospital coordinates from their ZIP center (or their city's center when the ZIP has no Census area)

Usage (from the repo root):
    python3 scripts/near_me_data_to_sql.py backend/src/main/resources/db/migration/V14__load_healthcare_near_me_data.sql

As with the other generated migrations, write refreshed data to a NEW migration version instead of editing V14.
"""

import json
import os
import sys
import uuid

sys.path.insert(0, os.path.dirname(__file__))
from cms_hospitals_to_sql import title  # noqa: E402  (same name clean-up as the hospital data)

CLINIC_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, "https://vigilant-health-compass/community-health-centers")


def sql(value):
    if value is None or value == "":
        return "null"
    if isinstance(value, float):
        return repr(value)
    return "'" + str(value).replace("'", "''") + "'"


def values(rows):
    return ",\n".join("(" + ", ".join(row) + ")" for row in rows)


def main(dest):
    zips = json.load(open("data/wi_zip_centers_census.json"))
    places = json.load(open("data/wi_place_centers_census.json"))
    clinics = json.load(open("data/wi_community_health_centers_hrsa.json"))

    zip_rows = [[sql(z["zip"]), sql(z["latitude"]), sql(z["longitude"])] for z in zips["zips"]]
    place_rows = [[sql(p["name"]), sql(p["kind"]), sql("WI"), sql(p["latitude"]), sql(p["longitude"])]
                  for p in places["places"]]
    clinic_rows = [[
        sql(str(uuid.uuid5(CLINIC_NAMESPACE, c["site_id"]))), sql(c["site_id"]), sql(clean_name(c["name"])),
        sql(title(c["organization"])), sql(c["address"]), sql(c["city"]), sql(c["state"]), sql(c["postal_code"]),
        sql(c["phone"]), sql(normalize_url(c["website"])), sql(c["health_center_type"]),
        sql(float(c["latitude"])), sql(float(c["longitude"])),
    ] for c in clinics["sites"]]

    out = f"""-- GENERATED by scripts/near_me_data_to_sql.py -- do not edit by hand.
-- ZIP centers: {zips["source"]} ({zips["filter"]}), retrieved {zips["retrieved"]}.
-- City centers: {places["source"]}, retrieved {places["retrieved"]}.
-- Clinics: {clinics["source"]} ({clinics["filter"]}), retrieved {clinics["retrieved"]}.

insert into zip_centers (zip, latitude, longitude) values
{values(zip_rows)};

insert into place_centers (name, kind, state, latitude, longitude) values
{values(place_rows)};

insert into community_health_centers (id, hrsa_site_id, name, organization, address, city, state, postal_code, phone, website, health_center_type, latitude, longitude) values
{values(clinic_rows)};

-- Hospitals (CMS has no coordinates): use the ZIP center, else the center of the city with that name.
update hospitals h
set latitude = z.latitude, longitude = z.longitude
from zip_centers z
where z.zip = left(h.postal_code, 5);

update hospitals h
set latitude = p.latitude, longitude = p.longitude
from place_centers p
where h.latitude is null and lower(p.name) = lower(h.city) and p.state = h.state;
"""
    with open(dest, "w") as f:
        f.write(out)
    print(f"Wrote {dest}: {len(zip_rows)} ZIP centers, {len(place_rows)} city centers, {len(clinic_rows)} clinics")


def clean_name(name):
    """Most HRSA site names are mixed case already; only clean up the ALL-CAPS ones."""
    return title(name) if name.isupper() else name


def normalize_url(url):
    url = url.strip()
    if url and not url.lower().startswith(("http://", "https://")):
        url = "https://" + url
    return url


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
