#!/usr/bin/env python3
"""Generate a Flyway migration that loads wi_vet_costs.json into the clinic price tables (see V5).

Usage (from the repo root):
    python3 scripts/wi_vet_costs_to_sql.py wi_vet_costs.json \
        backend/src/main/resources/db/migration/V6__load_wi_vet_costs.sql

Flyway never re-runs an applied migration, so when the JSON is updated, write the output to a NEW
version (V7__..., etc.) that deletes the old rows first, instead of editing V6.
"""

import json
import re
import sys
import uuid

# Stable clinic ids: the same location always gets the same UUID, so regenerating is deterministic.
CLINIC_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, "https://vigilant-health-compass/clinics")
ZIP = re.compile(r"\b(\d{5})(?:-\d{4})?\s*$")


def sql(value):
    """Render a Python value as a SQL literal."""
    if value is None or value == "":
        return "null"
    if isinstance(value, (int, float)):
        return f"{value:.2f}"  # prices; integer columns use integer()
    return "'" + str(value).replace("'", "''") + "'"


def integer(value):
    return "null" if value is None else str(int(value))


def rows(values):
    return ",\n".join("(" + ", ".join(row) + ")" for row in values)


def main(src, dest):
    with open(src) as f:
        data = json.load(f)

    procedures = data["averages"]
    prices = data["clinic_prices"]

    clinics = {}
    for p in prices:
        clinic_id = str(uuid.uuid5(CLINIC_NAMESPACE, p["location"]))
        match = ZIP.search(p["address"])
        clinics.setdefault(clinic_id, [
            sql(clinic_id), sql(p["organization"]), sql(p["location"]), sql(p["provider_type"]),
            sql(p["address"]), sql(p["city"]), sql("WI"), sql(match.group(1) if match else None),
            sql(p["eligibility"]), sql(p["source_url"]),
        ])
        p["clinic_id"] = clinic_id

    procedure_rows = [[
        sql(a["procedure_id"]), sql(a["species"]), sql(a["category"]), sql(a["procedure"]),
        sql(None if a["avg_price"] is None else float(a["avg_price"])), sql(a["avg_basis"]),
        sql(a["us_avg"]), integer(a["posted_n"]), sql(a["posted_min"]), sql(a["posted_mean"]),
        sql(a["posted_max"]),
    ] for a in procedures]

    price_rows = [[
        sql(p["clinic_id"]), sql(p["species"]), sql(p["category"]), sql(p["service"]),
        sql(float(p["price"])), sql(float(p["price_high"])), sql(p["procedure_id"]), sql(p["note"]),
        sql(p["price_as_of"]), sql(p["date_checked"]),
    ] for p in prices]

    out = f"""-- GENERATED by scripts/wi_vet_costs_to_sql.py from wi_vet_costs.json -- do not edit by hand.
-- Data checked {data["date_checked"]}. Method: {data["method"]}
-- {len(clinics)} clinic locations, {len(procedures)} procedures, {len(prices)} clinic prices.

insert into clinics (id, organization, name, provider_type, address, city, state, postal_code, eligibility, source_url) values
{rows(clinics.values())};

insert into procedures (id, species, category, name, avg_price, avg_basis, us_avg, posted_n, posted_min, posted_mean, posted_max) values
{rows(procedure_rows)};

insert into clinic_prices (clinic_id, species, category, service, price, price_high, procedure_id, note, price_as_of, date_checked) values
{rows(price_rows)};
"""
    with open(dest, "w") as f:
        f.write(out)
    print(f"Wrote {dest}: {len(clinics)} clinics, {len(procedures)} procedures, {len(prices)} prices")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
